#!/bin/bash

xdg-mime default boxpackage.desktop application/vnd.debian.binary-package

if [ ! -d "$HOME/.config/boxpackage/" ]
then
	mkdir $HOME/.config/boxpackage/
fi
if [ -f "$HOME/.config/boxpackage/auth" ]
then
	rm -f $HOME/.config/boxpackage/auth
fi
touch $HOME/.config/boxpackage/auth
echo "su" > $HOME/.config/boxpackage/auth


su root -c '/usr/lib64/boxpackage/init'
