#!/bin/bash

xdg-mime default boxpackage.desktop application/vnd.debian.binary-package

if [ ! -z $1 ] 
then

	if [ $(whoami) = "root" ]
	then
		/usr/lib64/boxpackage/init $1
		exit
	fi

	if [ -f "$HOME/.config/boxpackage/auth" ]
	then
		Auth=$(cat $HOME/.config/boxpackage/auth)
		if [ Auth = "sudo" ]
		then
			sudo /usr/lib64/boxpackage/init $1
		fi
		if [ Auth = "pkexec" ]
		then
			pkexec env DISPLAY=$DISPLAY XAUTHORITY=$XAUTHORITY /usr/lib64/boxpackage/init
		fi
		if [ Auth = "su" ]
		then
			su root -c '/usr/lib64/boxpackage/init'
		fi
	else
		pkexec env DISPLAY=$DISPLAY XAUTHORITY=$XAUTHORITY /usr/lib64/boxpackage/init
	fi
	
else
	echo "Error, waiting \$1"
fi
